### ISSUE TITLE
Disregarded list

### ISSUE THREAD

**Issue by julioasoares** [GalaxyDigitalLLC/Financial-Industry-Electricity-Balance#3]
This research was very much needed and welcome.

I would just suggest we should add a chapter pointing out all financial system estimations that are being completely disregarded (along with best/worst educated guess cases).

for instance :

**Payments:**

Besides estimated Card Brands datacenters we completely disregarded other datacenters, devices and service providers such as:

* POS terminals
* Gateways service
* Acquirers service 
* Sub acquirers 
* Anti-fraud 

**Life cycle/Logistics**
* Money making
 * special papers production
 * counterfeit protection elements (holograms, water marks) production
 * printing, cutting, packaging
* Coins minting
* Money destruction
* Armored vehicles fleet mileage
* Clearing houses
* Commuting (all markets staff)

**Non banking activities and markets**
* Currency Exchange stores
* Forex markets
* Stock markets
* Brokerage
* Insurance
* Call centers
* Consulting providers
* Central Banks (mentioned) and other Financial and Regulatory authorities
* Cash register
* Other payment terminals (park meters, tickets, etc.)
... (I'd keep the list open)

**Comment by rrybarczyk** [comment]
In the interest of scope, we have excluded central banks, clearinghouses (like the DTCC), and other aspects of the traditional financial system from the above analysis. It is important to note that this audit is only a slice of the entire system—the overall energy usage of the banking system is unknown and externalities are excluded.

We opened sourced this to encourage others to add more.
